### ISSUE TITLE
词达人崩溃了 

### ISSUE THREAD

**Issue by sakuraMY** [Rain-shadow/cdr#11]
日志名称：MainThread
[Info] 词达人版本：1.10.2
[Info] https://gateway.vocabgo.com/Auth/Thirdpart/Authorize?{'return_url': 'https://app.vocabgo.com/overall/#/student/home', 'auth_type': 1, 'user_token': 'c28b9c5f55d38f239fede923e7c1675d', 'timestamp': 1640518661567, 'versions': '1.2.0', 'sign': 'ebd452bb8ba0b2af060155383a1eb8c1'}
[Info] {"code":1,"msg":"success","data":{"redirect_url":"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a694105a6abbe6d&redirect_uri=https://gateway.vocabgo.com/Auth/Wechat/CodeCallback&response_type=code&scope=snsapi_userinfo&state=e9e1cc16a5f83514aad586136af481a1&connect_redirect=1#wechat_redirect"}}
[Info] user_token:c28b9c5f55d38f239fede923e7c1675d
[Info] 二维码已生成，将自动展示，请使用微信扫一扫进行词达人授权。成功后请关闭图片查看程序，若无法自动展示，用户可在“main目录\config目录”下找到“授权二维码.jpg，自行打开照片进行扫码授权”
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":1,"msg":"success","data":{"menu_list":[],"task_last":{"task_id":44589351,"release_id":1090602,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_1","list_id":"JJ_1_4_0","task_name":"B1 Unit4 Text","last_time":"2021-12-20","over_time":1640966340000,"grade":3,"update_time":1639932490787},"task_last_list":[{"task_id":44589351,"release_id":1090602,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_1","list_id":"JJ_1_4_0","task_name":"B1 Unit4 Text","last_time":"2021-12-20","over_time":1640966340000,"grade":3,"update_time":1639932490787}],"user_info":{"id":3919632,"nick_name":"陌语","avatar":"http://thirdwx.qlogo.cn/mmopen/oMmsjmGSlRPnrOYcTHrZECkhUoPOC2bU6F75L5S8aPia1Z4lTiavEBDBaugO7e4libQRt98sAurBAIMhfTfh723hSQyBIj4V3uL/132","mail":null,"student_name":"谢晖","student_code":"1520210323","course_id":"JJ_1","class_id":137103,"class_name":"护本3班","class_year":2021,"school_id":1996,"school_name":"右江民族医学院","profession":"","admin_class":"","integral_sign":55.0,"integral_study":741.8,"energy_pack":74.3,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1640518408199}}}
[Info] 授权成功

[Error]  Traceback (most recent call last):
   File "main.py", line 31, in <module>
   File "cdr\core.py", line 24, in do_homework
   File "cdr\url\url.py", line 57, in load_main
   File "cdr\url\url.py", line 77, in __load_resource
   File "cdr\request\request.py", line 60, in get
   File "cdr\request\request.py", line 39, in __judge_code
 NetworkError: 网络请求未成功:
code:404
url:https://app.vocabgo.com/student/css/app.1.210301.2.1614587768011.css?v=1.210301.2
msg:<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

[Error] 词达人自己崩了！<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

**Comment by Rain-shadow** [comment]
最新版到1.10.10了，建议更新最新版后尝试
