### ISSUE TITLE
考虑添加web方式的交互

### ISSUE THREAD

**Issue by RockChinQ** [Rain-shadow/cdr#14]
若是把这个机器人放在云服务器上进行长时间工作，实现一个web接口进行交互也许不错？

**Comment by Rain-shadow** [comment]
1.我不会python的服务端开发
2.现有的代码体系结构不适合增加web接口，只有少部分类可以被复用，主要流程都需要推倒重构
3.个人最近抽不出时间来大改，只能抽空修复一下bug

**Comment by RockChinQ** [comment]
> 1.我不会python的服务端开发
> 2.现有的代码体系结构不适合增加web接口，只有少部分类可以被复用，主要流程都需要推倒重构
> 3.个人最近抽不出时间来大改，只能抽空修复一下bug

感谢回复！
