### ISSUE TITLE
想请教一下这种情况是词达人自己崩了还是脚本失效了？

### ISSUE THREAD

**Issue by xiaojianqaq** [Rain-shadow/cdr#15]
![image](https://user-images.githubusercontent.com/46419880/157844562-4383a831-7e42-4838-ba8b-7c153e3d6627.png)

**Comment by Rain-shadow** [comment]
请指出软件版本，最好能附上详细日志。
如果版本是1..10.10，那可能是某些接口失效导致，若不是该版本，请更新到最新版尝试

**Comment by xiaojianqaq** [comment]
尝试过1.10.2与1.10，均有这个报错，用了1.9.16这个版本之后恢复正常，作者可以考虑更新新版的接口

**Comment by Rain-shadow** [comment]
没道理旧版能用新版不行，能附上详细日志么，那样我就能知道是哪个接口出的问题

**Comment by xiaojianqaq** [comment]
日志名称：MainThread
[Info] 词达人版本：1.10.2
[Info] 尝试复用token
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 曾用token已失效，重新执行授权流程！
[Info] https://gateway.vocabgo.com/Auth/Thirdpart/Authorize?{'return_url': 'https://app.vocabgo.com/overall/#/student/home', 'auth_type': 1, 'user_token': '3fea5a8ed3305825276bccc78de9272d', 'timestamp': 1647484335286, 'versions': '1.2.0', 'sign': 'd1fcf0ae4affa938c0232fbe0afc39d6'}
[Info] {"code":1,"msg":"success","data":{"redirect_url":"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a694105a6abbe6d&redirect_uri=https://gateway.vocabgo.com/Auth/Wechat/CodeCallback&response_type=code&scope=snsapi_userinfo&state=ebc3e0f5d1b171cb057e5b0c6644471c&connect_redirect=1#wechat_redirect"}}
[Info] user_token:3fea5a8ed3305825276bccc78de9272d
[Info] 二维码已生成，将自动展示，请使用微信扫一扫进行词达人授权。成功后请关闭图片查看程序，若无法自动展示，用户可在“main目录\config目录”下找到“授权二维码.jpg，自行打开照片进行扫码授权”
[Info] {"code":1,"msg":"success","data":{"menu_list":[],"task_last":{"task_id":48022590,"release_id":1160538,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_1","list_id":"JJ_1_3_0","task_name":"B1 Unit3 Text","last_time":"2022-03-12","over_time":1647661763880,"grade":3,"update_time":1647069244573},"task_last_list":[{"task_id":48022590,"release_id":1160538,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_1","list_id":"JJ_1_3_0","task_name":"B1 Unit3 Text","last_time":"2022-03-12","over_time":1647661763880,"grade":3,"update_time":1647069244573},{"task_id":47030705,"release_id":null,"study_type":1,"task_type":3,"contest_type":null,"course_id":"JJ_2","list_id":"JJ_2_1_0","task_name":"B2 Unit1 Text","last_time":"2022-03-11","over_time":0,"grade":3,"update_time":1647005852507}],"user_info":{"id":4253790,"nick_name":"\uD83C\uDF4B","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTK99GvarH6IGSiaTJxbTficW7dhxrNB4aJribNZg5gObBYVVZfwn1Jtw2tthfxxYz7icTnYFFxicyibkxeg/132","mail":null,"student_name":"\uD83C\uDF4B","student_code":"0","course_id":"JJ_2","class_id":147691,"class_name":"网络工程B21-3","class_year":2021,"school_id":693,"school_name":"上海建桥学院","profession":"","admin_class":"","integral_sign":130.0,"integral_study":994.7,"energy_pack":104.0,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1647484338288}}}
[Info] 授权成功

[Error]  Traceback (most recent call last):
   File "main.py", line 31, in <module>
   File "cdr\core.py", line 24, in do_homework
   File "cdr\url\url.py", line 57, in load_main
   File "cdr\url\url.py", line 77, in __load_resource
   File "cdr\request\request.py", line 60, in get
   File "cdr\request\request.py", line 39, in __judge_code
 NetworkError: 网络请求未成功:
code:404
url:https://app.vocabgo.com/student/css/app.1.210301.2.1614587768011.css?v=1.210301.2
msg:<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>



[Error] 词达人自己崩了！<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

**Comment by kinysun** [comment]
同样的问题 希望修复

**Comment by Rain-shadow** [comment]
这是之前不确定词达人风控规则时，我就干脆把他加载的js和css文件也同步请求了一次，现在在 4969dc3 中已经删除了该伪装，你可以拉取最新代码尝试。
该issue我就先关闭了，如果之后问题仍然存在，请reopen该issue

**Comment by xiaojianqaq** [comment]
感谢作者，自行编译最新版本之后问题已经得到修复了，exe文件的旧版本已经弃用啦

**Comment by xiaojianqaq** [comment]
另外在刷完一个任务之后选择下一个任务的时候会报以下错误，但是重启软件之后还是能继续刷的，下面是错误日志

[Info] 开始做【B2 Unit1 Reading1】，目标分数：100
[Info] 题库装载完毕！
[Info] 模拟加载流程
[Info] {"code":0,"msg":"对不起，创建任务信息失败，请返回首页重新加载","data":null}
{'task_id': -1, 'course_id': 'JJ_2', 'list_id': 'JJ_2_1_1', 'timestamp': 1647499298225, 'versions': '1.2.0'}
[Info] {"code":0,"msg":"对不起，创建任务信息失败，请返回首页重新加载","data":null}

[Error]  Traceback (most recent call last):
   File "main.py", line 31, in <module>
   File "cdr\core.py", line 65, in do_homework
   File "asyncio\base_events.py", line 641, in run_until_complete
   File "cdr\test\myself_task.py", line 67, in run
   File "cdr\test\cdr_task.py", line 48, in start_task
   File "cdr\aio\tasks.py", line 31, in run
   File "cdr\aio\tasks.py", line 49, in __work
   File "cdr\aio\tasks.py", line 37, in __work
   File "cdr\test\myself_task.py", line 109, in do_task
 TypeError: 'NoneType' object is not subscriptable

[Error] 'NoneType' object is not subscriptable
[Error] 未知异常，请上报此错误（error-last.txt）给GM
[Error] 你可以在“main\log\”下找到error-last.txt

**Comment by xiaojianqaq** [comment]
答题的时候会出现答案错误的问题，不清楚是我编译的问题还是源代码的逻辑问题，还请作者大大多指点指点，本人学的是C，对python并没有很多的基础，错误代码如下

[Info] {"code":1,"msg":"处理成功！","data":{"topic_code":"j1R+gZhrWo6DfnrEZ5Vol2lbXlrGqpitmpecoVeRlmhgmZZwYGqOaGpocGpxbpSNa2iWaGhncG1ljWu/ZGhiaWKUkVeWhpNgvIVqVpS/YGNqa3BtcZuYZ2SebG+U","over_status":1,"answer_result":2,"answer_corrects":[3],"clean_status":1,"word":"drawback"}}
[Warning] {'code': 1, 'msg': '处理成功！', 'data': {'topic_code': 'j1R+gZhrWo6DfnrEZ5Vol2lbXlrGqpitmpecoVeRlmhgmZZwYGqOaGpocGpxbpSNa2iWaGhncG1ljWu/ZGhiaWKUkVeWhpNgvIVqVpS/YGNqa3BtcZuYZ2SebG+U', 'over_status': 1, 'answer_result': 2, 'answer_corrects': [3], 'clean_status': 1, 'word': 'drawback'}}

[Warning] 答案错误！
[Warning] {'answer': '1', 'topic_code': 'j1R+gZhrWo6DfnrEZ5Vol2lbXlrGqpitmpecoVeRlmhgmZZwYGqOaGpocGpxbpSNa2iWaGhncG1ljWu/ZGhiaWKUkVeWhpNgvMCWYGiYaGlocHJwa5aaa2nC', 'timestamp': 1647499744913, 'versions': '1.2.0', 'sign': 'eeef7e0155cd6b890ce101a233a456b6'}
[Warning] 请携带error-last.txt寻找GM排除适配问题
[Warning] 你可以在“main\log\”下找到error-last.txt

**Comment by Rain-shadow** [comment]
> 答题的时候会出现答案错误的问题，不清楚是我编译的问题还是源代码的逻辑问题，还请作者大大多指点指点，本人学的是C，对python并没有很多的基础，错误代码如下
> 
> [Info] {"code":1,"msg":"处理成功！","data":{"topic_code":"j1R+gZhrWo6DfnrEZ5Vol2lbXlrGqpitmpecoVeRlmhgmZZwYGqOaGpocGpxbpSNa2iWaGhncG1ljWu/ZGhiaWKUkVeWhpNgvIVqVpS/YGNqa3BtcZuYZ2SebG+U","over_status":1,"answer_result":2,"answer_corrects":[3],"clean_status":1,"word":"drawback"}} [Warning] {'code': 1, 'msg': '处理成功！', 'data': {'topic_code': 'j1R+gZhrWo6DfnrEZ5Vol2lbXlrGqpitmpecoVeRlmhgmZZwYGqOaGpocGpxbpSNa2iWaGhncG1ljWu/ZGhiaWKUkVeWhpNgvIVqVpS/YGNqa3BtcZuYZ2SebG+U', 'over_status': 1, 'answer_result': 2, 'answer_corrects': [3], 'clean_status': 1, 'word': 'drawback'}}
> 
> [Warning] 答案错误！ [Warning] {'answer': '1', 'topic_code': 'j1R+gZhrWo6DfnrEZ5Vol2lbXlrGqpitmpecoVeRlmhgmZZwYGqOaGpocGpxbpSNa2iWaGhncG1ljWu/ZGhiaWKUkVeWhpNgvMCWYGiYaGlocHJwa5aaa2nC', 'timestamp': 1647499744913, 'versions': '1.2.0', 'sign': 'eeef7e0155cd6b890ce101a233a456b6'} [Warning] 请携带error-last.txt寻找GM排除适配问题 [Warning] 你可以在“main\log\”下找到error-last.txt

答案错误的相关因素太多了，和题型有关（查题逻辑不一样）、和题库有关、和题目有关、和选项有关，单给附近的日志完全没法处理。这得需要详细日志

**Comment by Rain-shadow** [comment]
> 另外在刷完一个任务之后选择下一个任务的时候会报以下错误，但是重启软件之后还是能继续刷的，下面是错误日志
> 
> [Info] 开始做【B2 Unit1 Reading1】，目标分数：100 [Info] 题库装载完毕！ [Info] 模拟加载流程 [Info] {"code":0,"msg":"对不起，创建任务信息失败，请返回首页重新加载","data":null} {'task_id': -1, 'course_id': 'JJ_2', 'list_id': 'JJ_2_1_1', 'timestamp': 1647499298225, 'versions': '1.2.0'} [Info] {"code":0,"msg":"对不起，创建任务信息失败，请返回首页重新加载","data":null}
> 
> [Error] Traceback (most recent call last): File "main.py", line 31, in File "cdr\core.py", line 65, in do_homework File "asyncio\base_events.py", line 641, in run_until_complete File "cdr\test\myself_task.py", line 67, in run File "cdr\test\cdr_task.py", line 48, in start_task File "cdr\aio\tasks.py", line 31, in run File "cdr\aio\tasks.py", line 49, in __work File "cdr\aio\tasks.py", line 37, in __work File "cdr\test\myself_task.py", line 109, in do_task TypeError: 'NoneType' object is not subscriptable
> 
> [Error] 'NoneType' object is not subscriptable [Error] 未知异常，请上报此错误（error-last.txt）给GM [Error] 你可以在“main\log\”下找到error-last.txt

至于这个问题，能说一下详细的复现步骤么

**Comment by Rain-shadow** [comment]
还有，若是问题与该issue不同，请新开一个issue。该issue已关闭，请勿继续回复
