### ISSUE TITLE
不知道为啥报错了

### ISSUE THREAD

**Issue by diary-OvO** [Rain-shadow/cdr#16]
[Error]'CET4_hx:CET4_hx_21'

**Comment by diary-OvO** [comment]
这种情况是我机子的问题还是其他的问题qaq

**Comment by Rain-shadow** [comment]
请指出软件版本，并附上详细日志。单这么一个东西，我也不清楚是什么情况啊

**Comment by diary-OvO** [comment]
[log.zip](https://github.com/Rain-shadow/cdr/files/8262712/log.zip)
软件版本应该是最新的那个
