### ISSUE TITLE
不会python怎么操作呀？

### ISSUE THREAD

**Issue by TomfengGitHub** [Rain-shadow/cdr#19]
有没有详细一点儿的步骤

**Comment by Harry2336** [comment]
+1

**Comment by FinchOrigin** [comment]
https://github.com/Rain-shadow/cdr/blob/f1f055c02b7761ba1b354a6f99c5e00ef46faba5/cdr/core.py#L56

**Comment by Rain-shadow** [comment]
找个会Python的用pyinstaller编译成exe使用

**Comment by wzwtt** [comment]
> 有没有详细一点儿的步骤

[Uploading main.exe…]()

**Comment by wzwtt** [comment]
> 有没有详细一点儿的步骤

[main.zip](https://github.com/Rain-shadow/cdr/files/8425211/main.zip)
解压双击exe就可以用了
