### ISSUE TITLE
需要一直按1跳过任务，有时还会显示服务器繁忙，有解决方法吗？

### ISSUE THREAD

**Issue by Dongdii** [Rain-shadow/cdr#21]
![c1c7f3688a20367c4c5d91c2c3943ee](https://user-images.githubusercontent.com/98158133/161668351-e2384f9e-cbfe-43fc-a435-0aa86d15bfec.png)
![4a39e4cbdc676d22d6ed13a55faf9cc](https://user-images.githubusercontent.com/98158133/161668354-b14982c8-9cf7-47ce-bd33-853ef1878982.png)
![36cbc27c6e120b007caacd3b5fe08c9](https://user-images.githubusercontent.com/98158133/161668358-eb098274-e732-4780-a56d-e14cfd379144.png)

**Comment by Dongdii** [comment]
版本1.10.12pre

**Comment by Rain-shadow** [comment]
duplicate by #20
