### ISSUE TITLE
未知异常

### ISSUE THREAD

**Issue by MirrAKe** [Rain-shadow/cdr#24]
![image](https://user-images.githubusercontent.com/76761109/162144504-f22350ed-768a-4933-88c6-4637f2774e1e.png)
日志名称：MainThread
[Info] 词达人版本：1.10.11
[Info] 尝试复用token
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 曾用token已失效，重新执行授权流程！
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] https://gateway.vocabgo.com/Auth/Thirdpart/Authorize?{'return_url': 'https://app.vocabgo.com/overall/#/student/home', 'auth_type': 1, 'user_token': '032044dfa3c27c7ac4e8b2826274d8ce', 'timestamp': 1649316066815, 'versions': '1.2.0', 'sign': '9d233305699cf64bc1b75c8fcb30b8be'}
[Info] {"code":1,"msg":"success","data":{"redirect_url":"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a694105a6abbe6d&redirect_uri=https://gateway.vocabgo.com/Auth/Wechat/CodeCallback&response_type=code&scope=snsapi_userinfo&state=5b3f21e035e6ff59a039dcab38470322&connect_redirect=1#wechat_redirect"}}
[Info] user_token:032044dfa3c27c7ac4e8b2826274d8ce
[Info] 二维码已生成，将自动展示，请使用微信扫一扫进行词达人授权。成功后请关闭图片查看程序，若无法自动展示，用户可在“main目录\config目录”下找到“授权二维码.jpg，自行打开照片进行扫码授权”
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
[Info] {"code":11003,"msg":"需安全验证！","data":null}
[Info] 等待授权中......
1. 继续等待
2. 重新生成二维码

0. 返回上一级
[Info] {"code":1,"msg":"success","data":{"menu_list":[],"task_last":{"task_id":50808582,"release_id":1243471,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_4","list_id":"List_NULL","task_name":"A4-电气U3背词","last_time":"2022-04-01","over_time":1649210820000,"grade":3,"update_time":1648776960932},"task_last_list":[{"task_id":50808582,"release_id":1243471,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_4","list_id":"List_NULL","task_name":"A4-电气U3背词","last_time":"2022-04-01","over_time":1649210820000,"grade":3,"update_time":1648776960932}],"user_info":{"id":1680104,"nick_name":"一谭清泓平如镜","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epkn4Ikasp2Ku51PyU5nbxSWzgSk9jJxx9HcfZlQrANUA5cV4U3s2ichQIs1Xic29siaK6S8Y6QXM0RQ/132","mail":"","student_name":"谭泓镜","student_code":"2007720127","course_id":"JJ_4","class_id":155805,"class_name":"电气(3+4)2071","class_year":2020,"school_id":2661,"school_name":"青岛科技大学高密校区","profession":"","admin_class":"","integral_sign":545.0,"integral_study":4697.2,"energy_pack":462.2,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1649316112808},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"b73471f57d7f6d5f05678d252af70942","group_code":""}}}
[Info] 授权成功
[Info] {"code":1,"msg":"success","data":{"menu_list":[],"task_last":{"task_id":50808582,"release_id":1243471,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_4","list_id":"List_NULL","task_name":"A4-电气U3背词","last_time":"2022-04-01","over_time":1649210820000,"grade":3,"update_time":1648776960932},"task_last_list":[{"task_id":50808582,"release_id":1243471,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_4","list_id":"List_NULL","task_name":"A4-电气U3背词","last_time":"2022-04-01","over_time":1649210820000,"grade":3,"update_time":1648776960932}],"user_info":{"id":1680104,"nick_name":"一谭清泓平如镜","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epkn4Ikasp2Ku51PyU5nbxSWzgSk9jJxx9HcfZlQrANUA5cV4U3s2ichQIs1Xic29siaK6S8Y6QXM0RQ/132","mail":"","student_name":"谭泓镜","student_code":"2007720127","course_id":"JJ_4","class_id":155805,"class_name":"电气(3+4)2071","class_year":2020,"school_id":2661,"school_name":"青岛科技大学高密校区","profession":"","admin_class":"","integral_sign":545.0,"integral_study":4697.2,"energy_pack":462.2,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1649316112808},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"b73471f57d7f6d5f05678d252af70942","group_code":""}}}
[Info] {"code":1,"msg":"success","data":{"task_list":[],"total":0}}
[Info] {"code":1,"msg":"success","data":{"js_config":{"app_id":"wx2a694105a6abbe6d","url":"https://app.vocabgo.com/overall/","nonce_str":"cuBwmOT5getsryf1","timestamp":1649316118,"signature":"62a2813299a832caee4e34690a4d5b7f2cb8768e"}}}
[Info] WechatConfig:
[Info] {"code":1,"msg":"success","data":{"js_config":{"app_id":"wx2a694105a6abbe6d","url":"https://app.vocabgo.com/overall/","nonce_str":"cuBwmOT5getsryf1","timestamp":1649316118,"signature":"62a2813299a832caee4e34690a4d5b7f2cb8768e"}}}

谭泓镜（电气(3+4)2071）

1.班级任务
2.自选任务
3.删除本地授权信息（可更换账号刷题）
4.打开配置文件（关闭后将自动重载配置文件，记得保存）

#.加群1085739587免费获取最新版，更少的BUG、更高的准确率

0.退出

[Info] 重新加载配置文件中......
[Info] {"code":1,"msg":"success","data":{"menu_list":[],"task_last":{"task_id":50808582,"release_id":1243471,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_4","list_id":"List_NULL","task_name":"A4-电气U3背词","last_time":"2022-04-01","over_time":1649210820000,"grade":3,"update_time":1648776960932},"task_last_list":[{"task_id":50808582,"release_id":1243471,"study_type":2,"task_type":1,"contest_type":null,"course_id":"JJ_4","list_id":"List_NULL","task_name":"A4-电气U3背词","last_time":"2022-04-01","over_time":1649210820000,"grade":3,"update_time":1648776960932}],"user_info":{"id":1680104,"nick_name":","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epkn4Ikasp2Ku51PyU5nbxSWzgSk9jJxx9HcfZlQrANUA5cV4U3s2ichQIs1Xic29siaK6S8Y6QXM0RQ/132","mail":"","student_name":"","student_code":"2007720127","course_id":"JJ_4","class_id":155805,"class_name":"","class_year":2020,"school_id":2661,"school_name":"","profession":"","admin_class":"","integral_sign":545.0,"integral_study":4697.2,"energy_pack":462.2,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1649316112808},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"b73471f57d7f6d5f05678d252af70942","group_code":""}}}

1.班级任务
2.自选任务
3.删除本地授权信息（可更换账号刷题）
4.打开配置文件（关闭后将自动重载配置文件，记得保存）

#.加群1085739587免费获取最新版，更少的BUG、更高的准确率

0.退出

[Info] 正在加载任务列表中，请稍等......
[Info] {"code":1,"msg":"处理成功！","data":{"task_list":[{"task_id":-1,"task_type":2,"source":1,"release_id":1276788,"course_id":"JJ_4","task_name":"电气测试Unit3","course_img_url":"https://resource.vocabgo.com/Resource/Icon/JJ_4.jpg?version=1.2","score":0.0,"progress":0,"time_spent":0,"release_time":1649316350744,"start_time":1649316360000,"over_time":540000,"free":1,"over_status":2},{"task_id":50808582,"task_type":1,"source":2,"release_id":1243471,"course_id":"JJ_4","task_name":"A4-电气U3背词","course_img_url":"https://resource.vocabgo.com/Resource/Icon/JJ_4.jpg?version=1.2","score":100.0,"progress":100,"time_spent":402718,"release_time":1648717711479,"start_time":1648717647803,"over_time":493172197,"free":1,"over_status":3}],"total":2}}
[Info] [{'task_id': -1, 'task_type': 2, 'source': 1, 'release_id': 1276788, 'course_id': 'JJ_4', 'task_name': '电气测试Unit3', 'course_img_url': 'https://resource.vocabgo.com/Resource/Icon/JJ_4.jpg?version=1.2', 'score': 0.0, 'progress': 0, 'time_spent': 0, 'release_time': 1649316350744, 'start_time': 1649316360000, 'over_time': 540000, 'free': 1, 'over_status': 2}, {'task_id': 50808582, 'task_type': 1, 'source': 2, 'release_id': 1243471, 'course_id': 'JJ_4', 'task_name': 'A4-电气U3背词', 'course_img_url': 'https://resource.vocabgo.com/Resource/Icon/JJ_4.jpg?version=1.2', 'score': 100.0, 'progress': 100, 'time_spent': 402718, 'release_time': 1648717711479, 'start_time': 1648717647803, 'over_time': 493172197, 'free': 1, 'over_status': 3}]
[Info] {'task_id': -1, 'task_type': 2, 'source': 1, 'release_id': 1276788, 'course_id': 'JJ_4', 'task_name': '电气测试Unit3', 'course_img_url': 'https://resource.vocabgo.com/Resource/Icon/JJ_4.jpg?version=1.2', 'score': 0.0, 'progress': 0, 'time_spent': 0, 'release_time': 1649316350744, 'start_time': 1649316360000, 'over_time': 540000, 'free': 1, 'over_status': 2}
[Info] [测试][进行中] 电气测试Unit3 （0.0分）
[Info] {'task_id': 50808582, 'task_type': 1, 'source': 2, 'release_id': 1243471, 'course_id': 'JJ_4', 'task_name': 'A4-电气U3背词', 'course_img_url': 'https://resource.vocabgo.com/Resource/Icon/JJ_4.jpg?version=1.2', 'score': 100.0, 'progress': 100, 'time_spent': 402718, 'release_time': 1648717711479, 'start_time': 1648717647803, 'over_time': 493172197, 'free': 1, 'over_status': 3}
[Info] [学习][已过期] A4-电气U3背词 （100.0分）
请输入序号去选择要做的任务：

[Info] 1649316900.0
[Info] 04月07号 15:35:00
 1. [测试][进行中] 电气测试Unit3           （0.0分） 04月07号 15:35:00截止

#.  以空格分割可一次性选择多个任务
#.  你可以在“main\config\config.txt文件”中修改配置项以控分/修改做题时间间隔等

0.  选择全部任务

请输入序号：['1']
[Info] 预加载任务所需题库中......
[Info] {"code":0,"msg":"服务器繁忙1，请稍后重试","data":null}

[Error]  Traceback (most recent call last):
   File "main.py", line 31, in <module>
   File "cdr\core.py", line 61, in do_homework
   File "asyncio\base_events.py", line 642, in run_until_complete
   File "cdr\test\class_task.py", line 77, in run
   File "cdr\test\class_task.py", line 78, in <listcomp>
   File "cdr\test\cdr_task.py", line 54, in get_course_by_task
   File "cdr\test\cdr_task.py", line 70, in get_load_words
 TypeError: 'NoneType' object is not subscriptable

[Error] 'NoneType' object is not subscriptable
[Error] 未知异常，请上报此错误（error-last.txt）给GM
[Error] 你可以在“main\log\”下找到error-last.txt

**Comment by MirrAKe** [comment]
重开之后就好了

**Comment by Rain-shadow** [comment]
疑似在“已经获取到任务信息的情况下”，二次获取任务信息导致的请求失败，该问题已在代码中进行了修复，请拉取代码后直接执行，若该问题依旧存在，请重新reopen该issue
