### ISSUE TITLE
软件没法正常使用 好像有问题了

### ISSUE THREAD

**Issue by VINISME** [Rain-shadow/cdr#25]
![1649677922(1)](https://user-images.githubusercontent.com/103424147/162733924-bb822acc-15f4-47ee-a099-004641925a2b.jpg)

**Comment by Rain-shadow** [comment]
Release中早就不更新了，建议拉取代码直接运行

**Comment by Rain-shadow** [comment]
如果不会，看着这 https://github.com/Rain-shadow/cdr/issues/19#issuecomment-1090013565
