### ISSUE TITLE
请问大佬 用pyinstaller打包的时候是在cdr文件目录还是cdr-main目录下进行打包？

### ISSUE THREAD

**Issue by VINISME** [Rain-shadow/cdr#27]

**Comment by VINISME** [comment]
也就是说打包的时候具体打包那个文件成exe文件呢，纯小白 想自己动手丰衣足食试一试

**Comment by Rain-shadow** [comment]
main.py是入口文件，在他所属的目录下打包

**Comment by VINISME** [comment]
> 

具体是打包那个文件呢？

**Comment by VINISME** [comment]
请问大佬 那我需要在那个目录下打包哪个文件呢？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rain-shadow/cdr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月13日(星期三) 晚上11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Rain-shadow/cdr] 请问大佬 用pyinstaller打包的时候是在cdr文件目录还是cdr-main目录下进行打包？ (Issue #27)





 
main.py是入口文件，在他所属的目录下打包

**Comment by Rain-shadow** [comment]
你先自己写一个单文件的.py去打包，然后自己百度看多文件的pyinstaller如何进行打包
