### ISSUE TITLE
出错了，能加下联系方式我学学吗

### ISSUE THREAD

**Issue by 2446983152** [Rain-shadow/cdr#32]
![屏幕截图 2022-04-28 212236](https://user-images.githubusercontent.com/104574664/165764704-96680743-98ec-4446-85fa-152b6f0a0a3d.png)

**Comment by Rain-shadow** [comment]
请提供错误日志

**Comment by 2446983152** [comment]
[Uploading error-last.txt…]()

**Comment by 2446983152** [comment]
[error-last.txt](https://github.com/Rain-shadow/cdr/files/8589580/error-last.txt)
