### ISSUE TITLE
怎么打不开呀，提示报错了?

### ISSUE THREAD

**Issue by qipking** [Rain-shadow/cdr#6]
发生异常: ImportError
cannot import name '_imaging' from 'PIL' (C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\PIL\__init__.py)
  File "C:\projects\py\cdr-main\cdr\utils\verification_code.py", line 12, in <module>
    from PIL import Image

**Comment by Rain-shadow** [comment]
请安装第三方库
